# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.stepenLabel = QtWidgets.QLabel(parent=Dialog)
        self.stepenLabel.setObjectName("stepenLabel")
        self.verticalLayout.addWidget(self.stepenLabel)
        self.stepenLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.stepenLineEdit.setObjectName("stepenLineEdit")
        self.verticalLayout.addWidget(self.stepenLineEdit)
        self.zernoLabel = QtWidgets.QLabel(parent=Dialog)
        self.zernoLabel.setObjectName("zernoLabel")
        self.verticalLayout.addWidget(self.zernoLabel)
        self.zernoComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.zernoComboBox.setObjectName("zernoComboBox")
        self.zernoComboBox.addItem("")
        self.zernoComboBox.addItem("")
        self.verticalLayout.addWidget(self.zernoComboBox)
        self.vkusLabel = QtWidgets.QLabel(parent=Dialog)
        self.vkusLabel.setObjectName("vkusLabel")
        self.verticalLayout.addWidget(self.vkusLabel)
        self.vkusPlainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.vkusPlainTextEdit.setObjectName("vkusPlainTextEdit")
        self.verticalLayout.addWidget(self.vkusPlainTextEdit)
        self.priceLabel = QtWidgets.QLabel(parent=Dialog)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout.addWidget(self.priceLabel)
        self.priceSpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.priceSpinBox.setMinimum(0)
        self.priceSpinBox.setMaximum(5000)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.verticalLayout.addWidget(self.priceSpinBox)
        self.objemLabel = QtWidgets.QLabel(parent=Dialog)
        self.objemLabel.setObjectName("objemLabel")
        self.verticalLayout.addWidget(self.objemLabel)
        self.objemSpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.objemSpinBox.setMinimum(0)
        self.objemSpinBox.setMaximum(500)
        self.objemSpinBox.setObjectName("objemSpinBox")
        self.verticalLayout.addWidget(self.objemSpinBox)
        self.saveButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.nameLabel.setText(_translate("Dialog", "Название:"))
        self.stepenLabel.setText(_translate("Dialog", "Обжарка:"))
        self.zernoLabel.setText(_translate("Dialog", "Молотый/Зерна:"))
        self.zernoComboBox.setItemText(0, _translate("Dialog", "Молотый"))
        self.zernoComboBox.setItemText(1, _translate("Dialog", "Зерна"))
        self.vkusLabel.setText(_translate("Dialog", "Описание:"))
        self.priceLabel.setText(_translate("Dialog", "Цена:"))
        self.objemLabel.setText(_translate("Dialog", "Объем:"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
